<div id="content">
    <div class="info">
        <h1>Informace</h1>
        <div>
            <p>Tento projekt Animachat byl vytvořen pro potřeby maturitní práce. Slouží pro komunikaci skupiny lidí, kteří spolu potřebují komunikovat</p>
            <p>Vytvořeno v roce 2019</p>
            <p>Autor: Jaromír Feilhauer</p> 
        </div> 
    </div>
    <div class="help">
        <h1>Nápověda</h1>
        <div>
            <p>- Pokud ještě nemáte účet, zaregistrujte se na stránce <a href="/uzivatel">REGISTRACE</a></p>
            <p>- Pokud již účet máte, přihlaste se. Na hlavní stránce se zobrazí chat.</p>
            <p>- Novou zprávu odešlete stiskem ENTERU</p>
            <p>- Své údaje a heslo můžete změnit po přihlášení v záložce UŽIVATEL</p>
        </div> 
    </div>
</div>